<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  'built_in_version' => '7.5.0.0',
  'acceptable_sugar_versions' => array (
      0 => '',
  ),
  'acceptable_sugar_flavors' => array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
  ),
  'key' => 'asol',
  'author' => 'AlineaSol',
  'description' => 'AlineaSol Calendar Events is a CRM extension that provides your CRM with a very flexible, action-programmable calendar.',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'AlineaSol Calendar Events - Community Edition',
  'published_date' => '2016-10-24',
  'type' => 'module',
  'version' => '1.4.0',
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'AlineaSolCalendarEvents',
  'beans' =>
  array (
    0 =>
    array (
      'module' => 'asol_CalendarEvents',
      'class' => 'asol_CalendarEvents',
      'path' => 'modules/asol_CalendarEvents/asol_CalendarEvents.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' =>
  array (
  ),
  'relationships' =>
  array (
  ),
  'image_dir' => '<basepath>/icons',
  'copy' =>
  array (
    0 =>
    array (
      'from' => '<basepath>/modules/asol_CalendarEvents',
      'to' => 'modules/asol_CalendarEvents',
    ),
    1 =>
    array (
      'from' => '<basepath>/custom',
      'to' => 'custom',
    ),
  ),
  'entrypoints' => array (
    array (
      'from' => '<basepath>/custom/entrypoints/asolCalendarEvents_registry.php',
      	'to_module' => 'application',
      ),
  ),
  'language' =>
  array (
    0 =>
    array (
      'from' => '<basepath>/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
  'pre_execute'=>array(
  		0 => '<basepath>/actions/pre_install.php',
  ),
  'post_execute'=>array(
		0 => '<basepath>/actions/post_install.php',
  ),
  'post_uninstall'=>array(
		0 => '<basepath>/actions/post_uninstall.php',
  ),
);