<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2012 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '6.5.22',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => '',
  'author' => 'Ivan',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Export',
  'published_date' => '2016-09-20 16:02:54',
  'type' => 'module',
  'version' => 1474387378,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Export',
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>\\metadata\\accounts_accountsMetaData.php',
    ),
    1 => 
    array (
      'meta_data' => '<basepath>\\metadata\\accounts_accounts_1MetaData.php',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/include/language/en_us.Export.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/include/language/es_es.Export.php',
      'to_module' => 'application',
      'language' => 'es_es',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/language/es_es.lang.php',
      'to_module' => 'Accounts',
      'language' => 'es_es',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/fact_Facturas/language/es_es.lang.php',
      'to_module' => 'fact_Facturas',
      'language' => 'es_es',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/fact_Items/language/es_es.lang.php',
      'to_module' => 'fact_Items',
      'language' => 'es_es',
    ),
  ),
  'custom_fields' => 
  array (
    'Accountscif_c' => 
    array (
      'id' => 'Accountscif_c',
      'name' => 'cif_c',
      'label' => 'LBL_CIF',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '9',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2011-07-18 13:12:14',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '1',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Accountscolegio_c' => 
    array (
      'id' => 'Accountscolegio_c',
      'name' => 'colegio_c',
      'label' => 'LBL_COLEGIO',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '60',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2011-07-18 13:13:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '1',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Accountscurso_c' => 
    array (
      'id' => 'Accountscurso_c',
      'name' => 'curso_c',
      'label' => 'LBL_CURSO',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '60',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2011-07-18 13:13:59',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '1',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Accountsasignaturas_c' => 
    array (
      'id' => 'Accountsasignaturas_c',
      'name' => 'asignaturas_c',
      'label' => 'LBL_ASIGNATURAS',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'Accounts',
      'type' => 'text',
      'max_size' => NULL,
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2011-07-18 13:15:10',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => '10',
      'ext3' => '20',
      'ext4' => NULL,
    ),
    'Accountsalumno_c' => 
    array (
      'id' => 'Accountsalumno_c',
      'name' => 'alumno_c',
      'label' => 'LBL_ALUMNO',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2011-07-18 13:15:59',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '1',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Accountsdescripcion_recibo_c' => 
    array (
      'id' => 'Accountsdescripcion_recibo_c',
      'name' => 'descripcion_recibo_c',
      'label' => 'LBL_DESCRIPCION_RECIBO',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'Accounts',
      'type' => 'text',
      'max_size' => NULL,
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2013-01-03 11:01:18',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => '4',
      'ext3' => '20',
      'ext4' => NULL,
    ),
    'Accountsrecibosino_c' => 
    array (
      'id' => 'Accountsrecibosino_c',
      'name' => 'recibosino_c',
      'label' => 'LBL_RECIBOSINO',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'Accounts',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '1',
      'default_value' => 'No',
      'date_modified' => '2013-01-03 11:08:46',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'recibosino_list',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Accountscantidad_recibo_c' => 
    array (
      'id' => 'Accountscantidad_recibo_c',
      'name' => 'cantidad_recibo_c',
      'label' => 'LBL_CANTIDAD_RECIBO',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'Accounts',
      'type' => 'currency',
      'max_size' => '26',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2013-01-03 11:32:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Accountscurrency_id' => 
    array (
      'id' => 'Accountscurrency_id',
      'name' => 'currency_id',
      'label' => 'LBL_CURRENCY',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'Accounts',
      'type' => 'currency_id',
      'max_size' => '36',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2013-01-03 11:32:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Accountsnumero_c' => 
    array (
      'id' => 'Accountsnumero_c',
      'name' => 'numero_c',
      'label' => 'LBL_NUMERO',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'Accounts',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '0',
      'date_modified' => '2014-03-26 19:02:07',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Accountsgrupo_c' => 
    array (
      'id' => 'Accountsgrupo_c',
      'name' => 'grupo_c',
      'label' => 'LBL_GRUPO',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'Accounts',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '1',
      'default_value' => 'ivema',
      'date_modified' => '2015-06-16 18:43:34',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'grupo_list',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Accountsncp_firmado_c' => 
    array (
      'id' => 'Accountsncp_firmado_c',
      'name' => 'ncp_firmado_c',
      'label' => 'LBL_NCP_FIRMADO',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'Accounts',
      'type' => 'bool',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '0',
      'date_modified' => '2016-08-24 19:08:25',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'Accountsncp_escaneado_c' => 
    array (
      'id' => 'Accountsncp_escaneado_c',
      'name' => 'ncp_escaneado_c',
      'label' => 'LBL_NCP_ESCANEADO',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'bool',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '0',
      'date_modified' => '2016-08-24 19:07:32',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'Accountsncp_entregado_c' => 
    array (
      'id' => 'Accountsncp_entregado_c',
      'name' => 'ncp_entregado_c',
      'label' => 'LBL_NCP_ENTREGADO',
      'comments' => '',
      'help' => '',
      'module' => 'Accounts',
      'type' => 'bool',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '0',
      'date_modified' => '2016-08-24 19:08:59',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => '',
      'ext2' => '',
      'ext3' => '',
      'ext4' => '',
    ),
    'fact_Facturasgasto_si_no_c' => 
    array (
      'id' => 'fact_Facturasgasto_si_no_c',
      'name' => 'gasto_si_no_c',
      'label' => 'LBL_GASTO_SI_NO',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'fact_Facturas',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => 'No',
      'date_modified' => '2011-07-18 13:25:55',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'gasto_si_no_list',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'fact_Facturasingreso_si_no_c' => 
    array (
      'id' => 'fact_Facturasingreso_si_no_c',
      'name' => 'ingreso_si_no_c',
      'label' => 'LBL_INGRESO_SI_NO',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'fact_Facturas',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => 'Si',
      'date_modified' => '2011-07-18 13:26:39',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'gasto_si_no_list',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'fact_Facturasnrecibo_c' => 
    array (
      'id' => 'fact_Facturasnrecibo_c',
      'name' => 'nrecibo_c',
      'label' => 'LBL_NRECIBO',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'fact_Facturas',
      'type' => 'varchar',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2011-07-18 13:27:00',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'fact_Facturasclasificacion_c' => 
    array (
      'id' => 'fact_Facturasclasificacion_c',
      'name' => 'clasificacion_c',
      'label' => 'LBL_CLASIFICACION',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'fact_Facturas',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => 'otros',
      'date_modified' => '2016-08-25 08:56:50',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'clasificacion_list',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'fact_Facturasmodo_pago_c' => 
    array (
      'id' => 'fact_Facturasmodo_pago_c',
      'name' => 'modo_pago_c',
      'label' => 'LBL_MODO_PAGO',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'fact_Facturas',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => 'otros',
      'date_modified' => '2014-03-28 11:56:15',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'modo_pago_list',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'fact_Facturasgrupo_c' => 
    array (
      'id' => 'fact_Facturasgrupo_c',
      'name' => 'grupo_c',
      'label' => 'LBL_GRUPO',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'fact_Facturas',
      'type' => 'enum',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => 'ivema',
      'date_modified' => '2014-08-27 08:15:49',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '1',
      'duplicate_merge' => '0',
      'reportable' => '1',
      'importable' => 'true',
      'ext1' => 'grupo_list',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
  ),
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/SearchFields.php',
      'to' => 'custom/modules/Accounts/metadata/SearchFields.php',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/SearchFields.php',
      'to' => 'custom/working/modules/Accounts/metadata/SearchFields.php',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/detailviewdefs.php',
      'to' => 'custom/modules/Accounts/metadata/detailviewdefs.php',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/detailviewdefs.php',
      'to' => 'custom/working/modules/Accounts/metadata/detailviewdefs.php',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/detailviewdefs.php.suback.php',
      'to' => 'custom/modules/Accounts/metadata/detailviewdefs.php.suback.php',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/detailviewdefs.php.suback.php',
      'to' => 'custom/working/modules/Accounts/metadata/detailviewdefs.php.suback.php',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/editviewdefs.php',
      'to' => 'custom/modules/Accounts/metadata/editviewdefs.php',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/Accounts/metadata/editviewdefs.php',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/editviewdefs.php.suback.php',
      'to' => 'custom/modules/Accounts/metadata/editviewdefs.php.suback.php',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/editviewdefs.php.suback.php',
      'to' => 'custom/working/modules/Accounts/metadata/editviewdefs.php.suback.php',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/listviewdefs.php',
      'to' => 'custom/modules/Accounts/metadata/listviewdefs.php',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/listviewdefs.php.suback.php',
      'to' => 'custom/modules/Accounts/metadata/listviewdefs.php.suback.php',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/listviewdefs.php.suback.php',
      'to' => 'custom/working/modules/Accounts/metadata/listviewdefs.php.suback.php',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/quickcreatedefs.php',
      'to' => 'custom/modules/Accounts/metadata/quickcreatedefs.php',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/quickcreatedefs.php',
      'to' => 'custom/working/modules/Accounts/metadata/quickcreatedefs.php',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/quickcreatedefs.php.suback.php',
      'to' => 'custom/modules/Accounts/metadata/quickcreatedefs.php.suback.php',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/quickcreatedefs.php.suback.php',
      'to' => 'custom/working/modules/Accounts/metadata/quickcreatedefs.php.suback.php',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/searchdefs.php',
      'to' => 'custom/modules/Accounts/metadata/searchdefs.php',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/searchdefs.php',
      'to' => 'custom/working/modules/Accounts/metadata/searchdefs.php',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/searchdefs.php.suback.php',
      'to' => 'custom/modules/Accounts/metadata/searchdefs.php.suback.php',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Accounts/metadata/searchdefs.php.suback.php',
      'to' => 'custom/working/modules/Accounts/metadata/searchdefs.php.suback.php',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/modules/fact_Facturas/metadata/SearchFields.php',
      'to' => 'custom/modules/fact_Facturas/metadata/SearchFields.php',
    ),
    22 => 
    array (
      'from' => '<basepath>/SugarModules/modules/fact_Facturas/metadata/SearchFields.php',
      'to' => 'custom/working/modules/fact_Facturas/metadata/SearchFields.php',
    ),
    23 => 
    array (
      'from' => '<basepath>/SugarModules/modules/fact_Facturas/metadata/detailviewdefs.php',
      'to' => 'custom/modules/fact_Facturas/metadata/detailviewdefs.php',
    ),
    24 => 
    array (
      'from' => '<basepath>/SugarModules/modules/fact_Facturas/metadata/detailviewdefs.php',
      'to' => 'custom/working/modules/fact_Facturas/metadata/detailviewdefs.php',
    ),
    25 => 
    array (
      'from' => '<basepath>/SugarModules/modules/fact_Facturas/metadata/editviewdefs.php',
      'to' => 'custom/modules/fact_Facturas/metadata/editviewdefs.php',
    ),
    26 => 
    array (
      'from' => '<basepath>/SugarModules/modules/fact_Facturas/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/fact_Facturas/metadata/editviewdefs.php',
    ),
    27 => 
    array (
      'from' => '<basepath>/SugarModules/modules/fact_Facturas/metadata/listviewdefs.php',
      'to' => 'custom/modules/fact_Facturas/metadata/listviewdefs.php',
    ),
    28 => 
    array (
      'from' => '<basepath>/SugarModules/modules/fact_Facturas/metadata/quickcreatedefs.php',
      'to' => 'custom/modules/fact_Facturas/metadata/quickcreatedefs.php',
    ),
    29 => 
    array (
      'from' => '<basepath>/SugarModules/modules/fact_Facturas/metadata/quickcreatedefs.php',
      'to' => 'custom/working/modules/fact_Facturas/metadata/quickcreatedefs.php',
    ),
    30 => 
    array (
      'from' => '<basepath>/SugarModules/modules/fact_Facturas/metadata/searchdefs.php',
      'to' => 'custom/modules/fact_Facturas/metadata/searchdefs.php',
    ),
    31 => 
    array (
      'from' => '<basepath>/SugarModules/modules/fact_Facturas/metadata/searchdefs.php',
      'to' => 'custom/working/modules/fact_Facturas/metadata/searchdefs.php',
    ),
    32 => 
    array (
      'from' => '<basepath>/SugarModules/modules/fact_Items/metadata/detailviewdefs.php',
      'to' => 'custom/modules/fact_Items/metadata/detailviewdefs.php',
    ),
    33 => 
    array (
      'from' => '<basepath>/SugarModules/modules/fact_Items/metadata/detailviewdefs.php',
      'to' => 'custom/working/modules/fact_Items/metadata/detailviewdefs.php',
    ),
    34 => 
    array (
      'from' => '<basepath>/SugarModules/modules/fact_Items/metadata/editviewdefs.php',
      'to' => 'custom/modules/fact_Items/metadata/editviewdefs.php',
    ),
    35 => 
    array (
      'from' => '<basepath>/SugarModules/modules/fact_Items/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/fact_Items/metadata/editviewdefs.php',
    ),
    36 => 
    array (
      'from' => '<basepath>/SugarModules/modules/fact_Items/metadata/listviewdefs.php',
      'to' => 'custom/modules/fact_Items/metadata/listviewdefs.php',
    ),
    37 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Accounts\\Ext\\language\\en_us.Contratos.php',
      'to' => 'custom\\Extension\\modules\\Accounts\\Ext\\language\\en_us.Contratos.php',
    ),
    38 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Accounts\\Ext\\language\\en_us.customaccounts_accounts.php',
      'to' => 'custom\\Extension\\modules\\Accounts\\Ext\\language\\en_us.customaccounts_accounts.php',
    ),
    39 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Accounts\\Ext\\language\\en_us.customaccounts_accounts_1.php',
      'to' => 'custom\\Extension\\modules\\Accounts\\Ext\\language\\en_us.customaccounts_accounts_1.php',
    ),
    40 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Accounts\\Ext\\language\\en_us.Hosting.php',
      'to' => 'custom\\Extension\\modules\\Accounts\\Ext\\language\\en_us.Hosting.php',
    ),
    41 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Accounts\\Ext\\language\\en_us.Regoluna_Facturas.php',
      'to' => 'custom\\Extension\\modules\\Accounts\\Ext\\language\\en_us.Regoluna_Facturas.php',
    ),
    42 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Accounts\\Ext\\language\\en_us.Servicio_Tecnico.php',
      'to' => 'custom\\Extension\\modules\\Accounts\\Ext\\language\\en_us.Servicio_Tecnico.php',
    ),
    43 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Accounts\\Ext\\language\\es_es.Contratos.php',
      'to' => 'custom\\Extension\\modules\\Accounts\\Ext\\language\\es_es.Contratos.php',
    ),
    44 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Accounts\\Ext\\language\\es_es.customaccounts_accounts.php',
      'to' => 'custom\\Extension\\modules\\Accounts\\Ext\\language\\es_es.customaccounts_accounts.php',
    ),
    45 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Accounts\\Ext\\language\\es_es.customaccounts_accounts_1.php',
      'to' => 'custom\\Extension\\modules\\Accounts\\Ext\\language\\es_es.customaccounts_accounts_1.php',
    ),
    46 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Accounts\\Ext\\language\\es_es.Hosting.php',
      'to' => 'custom\\Extension\\modules\\Accounts\\Ext\\language\\es_es.Hosting.php',
    ),
    47 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Accounts\\Ext\\language\\es_es.Regoluna_Facturas.php',
      'to' => 'custom\\Extension\\modules\\Accounts\\Ext\\language\\es_es.Regoluna_Facturas.php',
    ),
    48 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Accounts\\Ext\\language\\es_es.Servicio_Tecnico.php',
      'to' => 'custom\\Extension\\modules\\Accounts\\Ext\\language\\es_es.Servicio_Tecnico.php',
    ),
    49 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Accounts\\Ext\\Layoutdefs\\accounts_accounts_1_Accounts.php',
      'to' => 'custom\\Extension\\modules\\Accounts\\Ext\\Layoutdefs\\accounts_accounts_1_Accounts.php',
    ),
    50 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Accounts\\Ext\\Layoutdefs\\accounts_accounts_Accounts.php',
      'to' => 'custom\\Extension\\modules\\Accounts\\Ext\\Layoutdefs\\accounts_accounts_Accounts.php',
    ),
    51 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Accounts\\Ext\\Layoutdefs\\con_contratos_accounts_Accounts.php',
      'to' => 'custom\\Extension\\modules\\Accounts\\Ext\\Layoutdefs\\con_contratos_accounts_Accounts.php',
    ),
    52 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Accounts\\Ext\\Layoutdefs\\stive_ordenes_accounts_Accounts.php',
      'to' => 'custom\\Extension\\modules\\Accounts\\Ext\\Layoutdefs\\stive_ordenes_accounts_Accounts.php',
    ),
    53 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Accounts\\Ext\\Layoutdefs\\_overrideAccountfact_Facturasdefault.php',
      'to' => 'custom\\Extension\\modules\\Accounts\\Ext\\Layoutdefs\\_overrideAccountfact_Facturasdefault.php',
    ),
    54 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Accounts\\Ext\\Layoutdefs\\_overrideAccount_subpanel_con_contratos_accounts.php',
      'to' => 'custom\\Extension\\modules\\Accounts\\Ext\\Layoutdefs\\_overrideAccount_subpanel_con_contratos_accounts.php',
    ),
    55 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Accounts\\Ext\\Vardefs\\accounts_accounts_1_Accounts.php',
      'to' => 'custom\\Extension\\modules\\Accounts\\Ext\\Vardefs\\accounts_accounts_1_Accounts.php',
    ),
    56 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Accounts\\Ext\\Vardefs\\accounts_accounts_Accounts.php',
      'to' => 'custom\\Extension\\modules\\Accounts\\Ext\\Vardefs\\accounts_accounts_Accounts.php',
    ),
    57 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Accounts\\Ext\\Vardefs\\con_contratos_accounts_Accounts.php',
      'to' => 'custom\\Extension\\modules\\Accounts\\Ext\\Vardefs\\con_contratos_accounts_Accounts.php',
    ),
    58 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Accounts\\Ext\\Vardefs\\hos_hosting_accounts_Accounts.php',
      'to' => 'custom\\Extension\\modules\\Accounts\\Ext\\Vardefs\\hos_hosting_accounts_Accounts.php',
    ),
    59 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Accounts\\Ext\\Vardefs\\stive_ordenes_accounts_Accounts.php',
      'to' => 'custom\\Extension\\modules\\Accounts\\Ext\\Vardefs\\stive_ordenes_accounts_Accounts.php',
    ),
    60 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Accounts\\Ext\\Vardefs\\sugarfield_alumno_c.php',
      'to' => 'custom\\Extension\\modules\\Accounts\\Ext\\Vardefs\\sugarfield_alumno_c.php',
    ),
    61 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Accounts\\Ext\\Vardefs\\sugarfield_asignaturas_c.php',
      'to' => 'custom\\Extension\\modules\\Accounts\\Ext\\Vardefs\\sugarfield_asignaturas_c.php',
    ),
    62 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Accounts\\Ext\\Vardefs\\sugarfield_cantidad_recibo_c.php',
      'to' => 'custom\\Extension\\modules\\Accounts\\Ext\\Vardefs\\sugarfield_cantidad_recibo_c.php',
    ),
    63 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Accounts\\Ext\\Vardefs\\sugarfield_cif_c.php',
      'to' => 'custom\\Extension\\modules\\Accounts\\Ext\\Vardefs\\sugarfield_cif_c.php',
    ),
    64 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Accounts\\Ext\\Vardefs\\sugarfield_colegio_c.php',
      'to' => 'custom\\Extension\\modules\\Accounts\\Ext\\Vardefs\\sugarfield_colegio_c.php',
    ),
    65 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Accounts\\Ext\\Vardefs\\sugarfield_currency_id.php',
      'to' => 'custom\\Extension\\modules\\Accounts\\Ext\\Vardefs\\sugarfield_currency_id.php',
    ),
    66 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Accounts\\Ext\\Vardefs\\sugarfield_curso_c.php',
      'to' => 'custom\\Extension\\modules\\Accounts\\Ext\\Vardefs\\sugarfield_curso_c.php',
    ),
    67 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Accounts\\Ext\\Vardefs\\sugarfield_descripcion_recibo_c.php',
      'to' => 'custom\\Extension\\modules\\Accounts\\Ext\\Vardefs\\sugarfield_descripcion_recibo_c.php',
    ),
    68 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Accounts\\Ext\\Vardefs\\sugarfield_grupo_c.php',
      'to' => 'custom\\Extension\\modules\\Accounts\\Ext\\Vardefs\\sugarfield_grupo_c.php',
    ),
    69 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Accounts\\Ext\\Vardefs\\sugarfield_ncp_entregado_c.php',
      'to' => 'custom\\Extension\\modules\\Accounts\\Ext\\Vardefs\\sugarfield_ncp_entregado_c.php',
    ),
    70 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Accounts\\Ext\\Vardefs\\sugarfield_ncp_escaneado_c.php',
      'to' => 'custom\\Extension\\modules\\Accounts\\Ext\\Vardefs\\sugarfield_ncp_escaneado_c.php',
    ),
    71 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Accounts\\Ext\\Vardefs\\sugarfield_ncp_firmado_c.php',
      'to' => 'custom\\Extension\\modules\\Accounts\\Ext\\Vardefs\\sugarfield_ncp_firmado_c.php',
    ),
    72 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Accounts\\Ext\\Vardefs\\sugarfield_numero_c.php',
      'to' => 'custom\\Extension\\modules\\Accounts\\Ext\\Vardefs\\sugarfield_numero_c.php',
    ),
    73 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Accounts\\Ext\\Vardefs\\sugarfield_recibosino_c.php',
      'to' => 'custom\\Extension\\modules\\Accounts\\Ext\\Vardefs\\sugarfield_recibosino_c.php',
    ),
    74 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\CON_Contratos\\Ext\\language\\en_us.Contratos.php',
      'to' => 'custom\\Extension\\modules\\CON_Contratos\\Ext\\language\\en_us.Contratos.php',
    ),
    75 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\CON_Contratos\\Ext\\language\\es_es.Contratos.php',
      'to' => 'custom\\Extension\\modules\\CON_Contratos\\Ext\\language\\es_es.Contratos.php',
    ),
    76 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\CON_Contratos\\Ext\\Vardefs\\con_contratos_accounts_CON_Contratos.php',
      'to' => 'custom\\Extension\\modules\\CON_Contratos\\Ext\\Vardefs\\con_contratos_accounts_CON_Contratos.php',
    ),
    77 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\fact_Facturas\\Ext\\Layoutdefs\\_overridefact_Facturasfact_Itemsdefault.php',
      'to' => 'custom\\Extension\\modules\\fact_Facturas\\Ext\\Layoutdefs\\_overridefact_Facturasfact_Itemsdefault.php',
    ),
    78 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\fact_Facturas\\Ext\\Vardefs\\sugarfield_clasificacion_c.php',
      'to' => 'custom\\Extension\\modules\\fact_Facturas\\Ext\\Vardefs\\sugarfield_clasificacion_c.php',
    ),
    79 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\fact_Facturas\\Ext\\Vardefs\\sugarfield_date_closed.php',
      'to' => 'custom\\Extension\\modules\\fact_Facturas\\Ext\\Vardefs\\sugarfield_date_closed.php',
    ),
    80 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\fact_Facturas\\Ext\\Vardefs\\sugarfield_gasto_si_no_c.php',
      'to' => 'custom\\Extension\\modules\\fact_Facturas\\Ext\\Vardefs\\sugarfield_gasto_si_no_c.php',
    ),
    81 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\fact_Facturas\\Ext\\Vardefs\\sugarfield_grupo_c.php',
      'to' => 'custom\\Extension\\modules\\fact_Facturas\\Ext\\Vardefs\\sugarfield_grupo_c.php',
    ),
    82 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\fact_Facturas\\Ext\\Vardefs\\sugarfield_ingreso_si_no_c.php',
      'to' => 'custom\\Extension\\modules\\fact_Facturas\\Ext\\Vardefs\\sugarfield_ingreso_si_no_c.php',
    ),
    83 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\fact_Facturas\\Ext\\Vardefs\\sugarfield_modo_pago_c.php',
      'to' => 'custom\\Extension\\modules\\fact_Facturas\\Ext\\Vardefs\\sugarfield_modo_pago_c.php',
    ),
    84 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\fact_Facturas\\Ext\\Vardefs\\sugarfield_nrecibo_c.php',
      'to' => 'custom\\Extension\\modules\\fact_Facturas\\Ext\\Vardefs\\sugarfield_nrecibo_c.php',
    ),
    85 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\fact_Items\\Ext\\Vardefs\\sugarfield_tipo.php',
      'to' => 'custom\\Extension\\modules\\fact_Items\\Ext\\Vardefs\\sugarfield_tipo.php',
    ),
    86 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Relationships\\Layoutdefs\\accounts_accounts_1_Accounts.php',
      'to' => 'custom\\Extension\\modules\\Relationships\\Layoutdefs\\accounts_accounts_1_Accounts.php',
    ),
    87 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Relationships\\Layoutdefs\\accounts_accounts_Accounts.php',
      'to' => 'custom\\Extension\\modules\\Relationships\\Layoutdefs\\accounts_accounts_Accounts.php',
    ),
    88 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Relationships\\Relationships\\accounts_accountsMetaData.php',
      'to' => 'custom\\Extension\\modules\\Relationships\\Relationships\\accounts_accountsMetaData.php',
    ),
    89 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Relationships\\Relationships\\accounts_accounts_1MetaData.php',
      'to' => 'custom\\Extension\\modules\\Relationships\\Relationships\\accounts_accounts_1MetaData.php',
    ),
    90 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Relationships\\Vardefs\\accounts_accounts_1_Accounts.php',
      'to' => 'custom\\Extension\\modules\\Relationships\\Vardefs\\accounts_accounts_1_Accounts.php',
    ),
    91 => 
    array (
      'from' => '<basepath>\\Extension\\modules\\Relationships\\Vardefs\\accounts_accounts_Accounts.php',
      'to' => 'custom\\Extension\\modules\\Relationships\\Vardefs\\accounts_accounts_Accounts.php',
    ),
  ),
);